const produtos = [
    {
      id : 1,
      nome: "Banana",
      preco: 4,
      secao: "Hortifruit",
      categoria: "fruta",
      img: "./src/img/banana.png",
      promocao: true,
      precoPromocao: "1.00",
      componentes: ["Potassio", "Vitamina B6", "Vitamina C", "Folatos"],
    },
    {
      id : 2,
      nome: "Morango",
      preco: 7,
      secao: "Hortifruit",
      categoria: "fruta",
      img: "./src/img/morango.png",
      promocao: false,
      precoPromocao: "0",
      componentes: ["Fibras", "Vitamina C", "Calcio", "Ferro","Potassio"],
    },
    {
      id : 3,
      nome: "Maca",
      preco: 4,
      secao: "Hortifruit",
      categoria: "fruta",
      img: "./src/img/maca.png",
      promocao: true,
      precoPromocao: "1.50",
      componentes: ["Potassio", "Vitamina A", "Vitamina E", "Vitamina C"],
    },
    {
      id : 4,
      nome: "Pao",
      preco: 5,
      secao: "Panificadora",
      categoria: "Paes",
      img: "./src/img/pao.png",
      promocao: true,
      precoPromocao: "2.50",
      componentes: ["Cálcio", "Sódio", "Fibra Alimentar", "Proteinas"],
    },
    {
      id : 5,
      nome: "Leite",
      preco: 7,
      secao: "Laticinios",
      categoria: "Leite",
      img: "./src/img/leite.png",
      promocao: false,
      precoPromocao: "1.00",
      componentes: ["Carboidratos", "Proteinas","Gorduras totais"],
    },
    {
      id : 6,
      nome: "Yorgut de Morango",
      preco: 3,
      secao: "Laticinios",
      categoria: "Leite",
      img: "./src/img/yogurtdemorango.png",
      promocao: false,
      precoPromocao: "0",
      componentes: ["Fibras", "Vitamina C", "Calcio", "Ferro","Gorduras totais"],
    },
    {
      id : 7,
      nome: "Torta de Maca",
      preco: 7,
      secao: "Panificadora",
      categoria: "Sobremesa",
      img: "./src/img/tortademaca.png",
      promocao: true,
      precoPromocao: "1.50",
      componentes: ["Potassio", "Vitamina A", "Vitamina E", "Vitamina C"],
    },
    {
      id : 8,
      nome: "Bolo",
      preco: 10,
      secao: "Panificadora",
      categoria: "Sobremesa",
      img: "./src/img/bolo.png",
      promocao: false,
      precoPromocao: "1.00",
      componentes: ["Carboidratos", "Proteinas", "Gorduras totais","Fibras",],
    },
  ];